const mongoose = require('mongoose');
const dotenv = require('dotenv');
const path = require('path');

dotenv.config({ path: path.join(__dirname, '../../.env') });

const Bike = require('../models/Bike');
const SparePart = require('../models/SparePart');
const ServiceType = require('../models/ServiceType');

const cars = [
  {
    title: 'BMW 3 Series 320d M Sport',
    brand: 'BMW',
    model: '320d M Sport',
    year: 2023,
    type: 'new',
    condition: 'excellent',
    price: 5490000,
    discountedPrice: 5190000,
    kmDriven: 1200,
    engineCC: 1995,
    fuelType: 'petrol',
    description: 'The BMW 3 Series sets the benchmark for sporty driving pleasure in the premium sedan segment.',
    images: ['https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=800&auto=format&fit=crop'],
    features: ['Sunroof', 'Leather Seats', 'Navigation', 'Parking Sensors', 'LED Headlights'],
    location: { city: 'Mumbai', state: 'Maharashtra', pincode: '400001' },
    status: 'available',
    isApproved: true,
    isFeatured: true,
    bestSeller: true,
    stock: 3,
    specifications: { power: '190 bhp', torque: '400 Nm', transmission: '8-Speed Automatic', mileage: '20.37 kmpl' },
  },
  {
    title: 'Mercedes-Benz C-Class C200',
    brand: 'Mercedes-Benz',
    model: 'C200',
    year: 2023,
    type: 'new',
    condition: 'excellent',
    price: 5700000,
    discountedPrice: 5500000,
    kmDriven: 800,
    engineCC: 1496,
    fuelType: 'petrol',
    description: 'The Mercedes C-Class redefines luxury with cutting-edge technology and refined comfort.',
    images: ['https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?q=80&w=800&auto=format&fit=crop'],
    features: ['MBUX Infotainment', 'Burmester Sound', 'Ambient Lighting', 'Digital Cockpit'],
    location: { city: 'Delhi', state: 'Delhi', pincode: '110001' },
    status: 'available',
    isApproved: true,
    isFeatured: true,
    bestSeller: true,
    stock: 2,
    specifications: { power: '204 bhp', torque: '300 Nm', transmission: '9G-TRONIC', mileage: '16.9 kmpl' },
  },
  {
    title: 'Audi A4 Premium Plus',
    brand: 'Audi',
    model: 'A4 Premium Plus',
    year: 2022,
    type: 'used',
    condition: 'excellent',
    price: 4500000,
    discountedPrice: 4200000,
    kmDriven: 15000,
    engineCC: 1984,
    fuelType: 'petrol',
    description: 'The Audi A4 combines progressive design with powerful performance and advanced technology.',
    images: ['https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?q=80&w=800&auto=format&fit=crop'],
    features: ['Virtual Cockpit', 'Matrix LED', 'Bang & Olufsen Audio', 'Quattro AWD'],
    location: { city: 'Bangalore', state: 'Karnataka', pincode: '560001' },
    status: 'available',
    isApproved: true,
    isFeatured: true,
    bestSeller: false,
    stock: 1,
    specifications: { power: '190 bhp', torque: '320 Nm', transmission: '7-Speed DCT', mileage: '17.42 kmpl' },
  },
  {
    title: 'Toyota Fortuner Legender',
    brand: 'Toyota',
    model: 'Fortuner Legender',
    year: 2023,
    type: 'new',
    condition: 'excellent',
    price: 4200000,
    discountedPrice: 3950000,
    kmDriven: 500,
    engineCC: 2755,
    fuelType: 'petrol',
    description: 'The Toyota Fortuner Legender is the ultimate SUV combining rugged capability with urban sophistication.',
    images: ['https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?q=80&w=800&auto=format&fit=crop'],
    features: ['360 Camera', 'JBL Sound System', 'Wireless Charging', 'Connected Car Tech'],
    location: { city: 'Chennai', state: 'Tamil Nadu', pincode: '600001' },
    status: 'available',
    isApproved: true,
    isFeatured: true,
    bestSeller: true,
    stock: 4,
    specifications: { power: '204 bhp', torque: '500 Nm', transmission: '6-Speed Automatic', mileage: '14.4 kmpl' },
  },
  {
    title: 'Hyundai Creta SX(O)',
    brand: 'Hyundai',
    model: 'Creta SX(O)',
    year: 2024,
    type: 'new',
    condition: 'excellent',
    price: 2050000,
    discountedPrice: 1950000,
    kmDriven: 0,
    engineCC: 1482,
    fuelType: 'petrol',
    description: 'The all-new Hyundai Creta with bold design, ADAS safety features, and panoramic sunroof.',
    images: ['https://images.unsplash.com/photo-1544636331-e26879cd4d9b?q=80&w=800&auto=format&fit=crop'],
    features: ['ADAS Level 2', 'Panoramic Sunroof', 'Ventilated Seats', 'BOSE Sound'],
    location: { city: 'Hyderabad', state: 'Telangana', pincode: '500001' },
    status: 'available',
    isApproved: true,
    isFeatured: false,
    bestSeller: true,
    stock: 5,
    specifications: { power: '160 bhp', torque: '253 Nm', transmission: '7-Speed DCT', mileage: '21.4 kmpl' },
  },
  {
    title: 'Mahindra Thar Roxx',
    brand: 'Mahindra',
    model: 'Thar Roxx',
    year: 2024,
    type: 'new',
    condition: 'excellent',
    price: 1800000,
    discountedPrice: 1700000,
    kmDriven: 0,
    engineCC: 2184,
    fuelType: 'petrol',
    description: 'The Mahindra Thar Roxx – born wild, engineered for the city. 5-door adventure machine.',
    images: ['https://images.unsplash.com/photo-1502877338535-766e1452684a?q=80&w=800&auto=format&fit=crop'],
    features: ['4x4', 'Skyroof', 'Harman Kardon', 'ADAS', 'Terrain Modes'],
    location: { city: 'Pune', state: 'Maharashtra', pincode: '411001' },
    status: 'available',
    isApproved: true,
    isFeatured: true,
    bestSeller: true,
    stock: 6,
    specifications: { power: '175 bhp', torque: '370 Nm', transmission: '6-Speed Automatic', mileage: '15.2 kmpl' },
  },
  {
    title: 'Porsche 911 Carrera S',
    brand: 'Porsche',
    model: '911 Carrera S',
    year: 2021,
    type: 'used',
    condition: 'excellent',
    price: 17500000,
    discountedPrice: 16500000,
    kmDriven: 8000,
    engineCC: 2981,
    fuelType: 'petrol',
    description: 'The iconic Porsche 911 Carrera S – timeless design meets breathtaking performance.',
    images: ['https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=800&auto=format&fit=crop'],
    features: ['Sport Chrono Package', 'PASM', 'BOSE Surround', 'Sport Exhaust'],
    location: { city: 'Mumbai', state: 'Maharashtra', pincode: '400001' },
    status: 'available',
    isApproved: true,
    isFeatured: true,
    bestSeller: false,
    stock: 1,
    specifications: { power: '450 bhp', torque: '530 Nm', transmission: '8-Speed PDK', mileage: '11.2 kmpl' },
  },
  {
    title: 'Tata Nexon EV Max',
    brand: 'Tata',
    model: 'Nexon EV Max',
    year: 2024,
    type: 'new',
    condition: 'excellent',
    price: 1900000,
    discountedPrice: 1800000,
    kmDriven: 0,
    engineCC: 0,
    fuelType: 'electric',
    description: 'India\'s best-selling electric SUV with 437km range and fast charging.',
    images: ['https://images.unsplash.com/photo-1560958089-b8a1929cea89?q=80&w=800&auto=format&fit=crop'],
    features: ['437km Range', 'Fast Charging', 'Connected Car', 'iRA Technology'],
    location: { city: 'Pune', state: 'Maharashtra', pincode: '411001' },
    status: 'available',
    isApproved: true,
    isFeatured: false,
    bestSeller: true,
    stock: 4,
    specifications: { power: '143 bhp', torque: '250 Nm', transmission: 'Single-Speed Auto', mileage: '437 km range' },
  },
];

const parts = [
  {
    name: 'Bosch Ceramic Brake Pads (Front)',
    category: 'brakes',
    brand: 'Bosch',
    description: 'Premium ceramic brake pads for superior stopping power and reduced dust.',
    price: 3500,
    discountedPrice: 2999,
    images: ['https://images.unsplash.com/photo-1558618666-fcd25c85f82e?q=80&w=400&auto=format&fit=crop'],
    stock: 50,
    isActive: true,
    isFeatured: true,
    bestSeller: true,
    ratings: 4.5,
    numReviews: 128,
  },
  {
    name: 'Mobil 1 Synthetic Engine Oil 5W-30',
    category: 'engine_oil',
    brand: 'Mobil',
    description: 'Full synthetic motor oil for advanced full protection and performance.',
    price: 2800,
    discountedPrice: 2399,
    images: ['https://images.unsplash.com/photo-1635784063942-e0f7db01a6d2?q=80&w=400&auto=format&fit=crop'],
    stock: 100,
    isActive: true,
    isFeatured: true,
    bestSeller: true,
    ratings: 4.7,
    numReviews: 245,
  },
  {
    name: 'Philips X-tremeUltinon LED H7',
    category: 'lighting',
    brand: 'Philips',
    description: 'Upgrade your headlights with 200% brighter LED bulbs for safe night driving.',
    price: 4500,
    discountedPrice: 3999,
    images: ['https://images.unsplash.com/photo-1489824904134-891ab64532f1?q=80&w=400&auto=format&fit=crop'],
    stock: 35,
    isActive: true,
    isFeatured: true,
    bestSeller: false,
    ratings: 4.3,
    numReviews: 87,
  },
  {
    name: 'Michelin Primacy 4 Tyre 205/55 R16',
    category: 'tyres',
    brand: 'Michelin',
    description: 'Premium safety tyre with excellent wet grip and long-lasting performance.',
    price: 8500,
    discountedPrice: 7499,
    images: ['https://images.unsplash.com/photo-1578844251758-2f71da64c96f?q=80&w=400&auto=format&fit=crop'],
    stock: 20,
    isActive: true,
    isFeatured: false,
    bestSeller: true,
    ratings: 4.8,
    numReviews: 196,
  },
  {
    name: 'EXIDE InvaPlus Battery 65Ah',
    category: 'battery',
    brand: 'Exide',
    description: 'High cranking power automotive battery with 36-month warranty.',
    price: 6500,
    discountedPrice: 5799,
    images: ['https://images.unsplash.com/photo-1619642751034-765dfdf7c58e?q=80&w=400&auto=format&fit=crop'],
    stock: 30,
    isActive: true,
    isFeatured: true,
    bestSeller: true,
    ratings: 4.4,
    numReviews: 156,
  },
  {
    name: 'K&N High-Flow Air Filter',
    category: 'filters',
    brand: 'K&N',
    description: 'Washable and reusable high-performance air filter for increased horsepower.',
    price: 3200,
    discountedPrice: 2799,
    images: ['https://images.unsplash.com/photo-1486262715619-67b85e0b08d3?q=80&w=400&auto=format&fit=crop'],
    stock: 40,
    isActive: true,
    isFeatured: false,
    bestSeller: true,
    ratings: 4.6,
    numReviews: 112,
  },
];

const serviceTypes = [
  { value: 'general_service', label: 'General Service', price: '2999', desc: 'Complete car health checkup with oil change & filter replacement', isActive: true, order: 1 },
  { value: 'engine_tuning', label: 'Engine Tuning', price: '5999', desc: 'Performance tuning and engine diagnostics for optimal power', isActive: true, order: 2 },
  { value: 'brake_service', label: 'Brake Service', price: '3499', desc: 'Brake pad replacement, disc check, and fluid top-up', isActive: true, order: 3 },
  { value: 'ac_service', label: 'AC Service', price: '1999', desc: 'AC gas refill, cooling coil cleaning, and cabin filter change', isActive: true, order: 4 },
  { value: 'detailing', label: 'Premium Detailing', price: '7999', desc: 'Full interior & exterior detailing with ceramic coating', isActive: true, order: 5 },
  { value: 'battery_service', label: 'Battery Check', price: '499', desc: 'Battery health test, terminal cleaning, and replacement if needed', isActive: true, order: 6 },
  { value: 'tyre_service', label: 'Tyre Service', price: '1499', desc: 'Wheel alignment, balancing, and tyre rotation for even wear', isActive: true, order: 7 },
  { value: 'body_repair', label: 'Body Repair', price: '4999', desc: 'Dent removal, scratch repair, and paint touch-up', isActive: true, order: 8 },
];

async function seed() {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log('Connected to MongoDB');

    // Clear existing data
    await Bike.deleteMany({});
    await SparePart.deleteMany({});
    await ServiceType.deleteMany({});
    console.log('Cleared existing data');

    // Seed
    const createdCars = await Bike.insertMany(cars);
    console.log(`Seeded ${createdCars.length} cars`);

    const createdParts = await SparePart.insertMany(parts);
    console.log(`Seeded ${createdParts.length} spare parts`);

    const createdServices = await ServiceType.insertMany(serviceTypes);
    console.log(`Seeded ${createdServices.length} service types`);

    console.log('\nSeeding complete!');
    process.exit(0);
  } catch (err) {
    console.error('Seeding error:', err.message);
    process.exit(1);
  }
}

seed();
